server:
  port: 8080

spring:
  application:
    name: ManagementPerpustakaan

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/db_perpustakaan
    username: root
    password: rizal280697
